-- ===========================================================================
-- 02_unknown_members.sql - the UNKNOWN (-1) and NOT APPLICABLE (-2) members.
--
-- Every dimension gets two fixed rows, inserted with EXPLICIT surrogate keys
-- before any load runs:
--
--   -1  UNKNOWN         the source gave a key we could not resolve or infer
--   -2  NOT APPLICABLE  the relationship legitimately does not exist
--                       (an RFID session with no linked vehicle, for example)
--
-- The distinction matters. "We do not know which vehicle" is a data problem
-- worth measuring; "this session has no vehicle by design" is not. Collapsing
-- both into one member would make the first invisible.
--
-- Because these exist, EVERY fact foreign key can be NOT NULL. The payoff is
-- practical rather than doctrinal: JOINs never silently drop rows, COUNT(*)
-- means what it says, and "how many sessions have an unknown charge point"
-- becomes a query instead of a mystery.
--
-- Requires GENERATED BY DEFAULT AS IDENTITY on the surrogate key columns -
-- GENERATED ALWAYS would reject these explicit values. The identity sequences
-- start at 1, so a generated key can never collide with -1 or -2.
--
-- The open-ended validity range means a fact of ANY date resolves against
-- these members in a point-in-time join.
--
-- The BEGINNING-OF-TIME sentinel is '0001-01-01 00:00:00+00', not the
-- PostgreSQL '-infinity' that would be the obvious choice. -infinity is
-- correct in the database and UNREADABLE from Python: psycopg raises
-- "timestamp too small (before year 1)" the moment any code SELECTs the
-- column, which turns a perfectly good sentinel into a landmine for every
-- script, test and future reader. Year 1 is far enough in the past to serve
-- exactly the same purpose - any fact of any plausible date resolves against
-- it - and it round-trips through every client.
-- ===========================================================================

INSERT INTO core.dim_customer (
    customer_sk, customer_id, full_name_masked, customer_segment,
    subscription_plan, kyc_status, is_active,
    effective_from_utc, effective_to_utc, is_current, version_no, row_hash, dw_run_id
)
VALUES
(-1, 'UNKNOWN', 'Unknown', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', FALSE,
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000'),
(-2, 'NOT_APPLICABLE', 'Not applicable', 'NOT_APPLICABLE', 'NOT_APPLICABLE', 'NOT_APPLICABLE', FALSE,
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000')
ON CONFLICT (customer_sk) DO NOTHING;

INSERT INTO core.dim_station (
    station_sk, station_id, station_name, is_active,
    effective_from_utc, effective_to_utc, is_current, version_no, row_hash, dw_run_id
)
VALUES
(-1, 'UNKNOWN', 'Unknown', FALSE,
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000'),
(-2, 'NOT_APPLICABLE', 'Not applicable', FALSE,
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000')
ON CONFLICT (station_sk) DO NOTHING;

INSERT INTO core.dim_charge_point (
    charge_point_sk, charge_point_id, status,
    effective_from_utc, effective_to_utc, is_current, version_no, row_hash, dw_run_id
)
VALUES
(-1, 'UNKNOWN', 'UNKNOWN',
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000'),
(-2, 'NOT_APPLICABLE', 'NOT_APPLICABLE',
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000')
ON CONFLICT (charge_point_sk) DO NOTHING;

-- The tariff UNKNOWN member carries ZERO prices deliberately. A session that
-- cannot resolve a tariff produces revenue of 0 and is surfaced by the
-- FACT_UNKNOWN_MEMBER_RATIO rule - visibly missing rather than quietly priced
-- at some plausible-looking default that would poison a revenue total.
INSERT INTO core.dim_tariff_plan (
    tariff_plan_sk, tariff_plan_id, plan_name,
    price_per_kwh_inr, price_per_minute_inr, idle_fee_per_minute_inr,
    min_billable_kwh, gst_rate_pct, is_active,
    effective_from_utc, effective_to_utc, is_current, version_no, row_hash, dw_run_id
)
VALUES
(-1, 'UNKNOWN', 'Unknown', 0, 0, 0, 0, 0, FALSE,
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000'),
(-2, 'NOT_APPLICABLE', 'Not applicable', 0, 0, 0, 0, 0, FALSE,
 '0001-01-01 00:00:00+00', '9999-12-31 00:00:00+00', TRUE, 1, repeat('0', 64),
 '00000000-0000-0000-0000-000000000000')
ON CONFLICT (tariff_plan_sk) DO NOTHING;

INSERT INTO core.dim_vehicle (vehicle_sk, vehicle_id, make, model, vehicle_class, dw_run_id)
VALUES
(-1, 'UNKNOWN', 'Unknown', 'Unknown', 'UNKNOWN', '00000000-0000-0000-0000-000000000000'),
(-2, 'NOT_APPLICABLE', 'Not applicable', 'Not applicable', 'NOT_APPLICABLE',
 '00000000-0000-0000-0000-000000000000')
ON CONFLICT (vehicle_sk) DO NOTHING;

INSERT INTO core.dim_session_outcome (
    session_outcome_sk, session_status, stop_reason, auth_method, is_roaming,
    is_successful, is_interrupted, outcome_group
)
VALUES
(-1, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', FALSE, FALSE, FALSE, 'UNKNOWN')
ON CONFLICT (session_outcome_sk) DO NOTHING;
