-- ===========================================================================
-- 30_core_dims.sql - the dimensions of the star schema.
--
-- SURROGATE KEYS are GENERATED BY DEFAULT rather than ALWAYS, for one specific
-- reason: the unknown (-1) and not-applicable (-2) members must be inserted
-- with explicit keys. GENERATED ALWAYS would forbid that and force an
-- OVERRIDING SYSTEM VALUE clause at every seed site. The sequence still starts
-- at 1, so a generated key can never collide with a seeded one.
--
-- SCD2 INVARIANTS ARE ENFORCED BY THE SCHEMA, not by hope:
--   * PRIMARY KEY (sk)                        - facts reference only this
--   * UNIQUE (business_key, effective_from)   - no duplicate version starts
--   * partial UNIQUE (business_key) WHERE is_current
--                                             - TWO CURRENT ROWS IMPOSSIBLE
--   * CHECK (effective_to > effective_from)   - no inverted intervals
--   * CHECK (is_current = (effective_to = the open sentinel))
--                                             - the flag cannot drift from the
--                                               dates it is a shorthand for
--   * EXCLUDE ... tstzrange && (when btree_gist is available)
--                                             - NO OVERLAPPING HISTORY
--
-- The partial unique index prevents two current rows. It does NOT prevent
-- ZERO current rows - only the single-transaction merge does that, and the
-- DIM_NO_CURRENT_ROW quality rule verifies it after every run.
--
-- effective_to_utc is EXCLUSIVE. Half-open intervals [from, to) have no gaps
-- and no overlaps; inclusive bounds force you to subtract a microsecond
-- somewhere, and eventually you get it wrong.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- core.dim_date - Type 0, static, an IST business calendar.
--
-- Generated for 2023-2030 by sql/seed/00_dim_date.sql. Fiscal year follows the
-- Indian convention: FY2027 runs April 2026 to March 2027.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_date (
    date_key                  INT          NOT NULL,
    full_date                 DATE         NOT NULL,
    day_of_month              SMALLINT     NOT NULL,
    day_of_week               SMALLINT     NOT NULL,
    day_name                  VARCHAR(10)  NOT NULL,
    week_of_year              SMALLINT     NOT NULL,
    month_num                 SMALLINT     NOT NULL,
    month_name                VARCHAR(10)  NOT NULL,
    quarter_num               SMALLINT     NOT NULL,
    year_num                  SMALLINT     NOT NULL,
    fiscal_year               SMALLINT     NOT NULL,
    fiscal_quarter            SMALLINT     NOT NULL,
    is_weekend                BOOLEAN      NOT NULL,
    is_month_end              BOOLEAN      NOT NULL,
    is_quarter_end            BOOLEAN      NOT NULL,
    is_indian_public_holiday  BOOLEAN      NOT NULL DEFAULT FALSE,
    holiday_name              VARCHAR(60)  NULL,
    CONSTRAINT pk_dim_date PRIMARY KEY (date_key),
    CONSTRAINT uq_dim_date_full_date UNIQUE (full_date)
);

COMMENT ON TABLE core.dim_date IS
    'GRAIN: one row per calendar date, in the Asia/Kolkata business calendar. date_key is YYYYMMDD.';
COMMENT ON COLUMN core.dim_date.fiscal_year IS
    'Indian fiscal year, April-March. FY is labelled by its ENDING calendar year: 2026-04-01 falls in fiscal_year 2027.';
COMMENT ON COLUMN core.dim_date.is_indian_public_holiday IS
    'From a seeded, ILLUSTRATIVE list of national holidays. Not an authoritative calendar and the README says so.';

CREATE INDEX IF NOT EXISTS ix_dim_date_year_month ON core.dim_date (year_num, month_num);


-- ---------------------------------------------------------------------------
-- core.dim_hour - Type 0, static, 24 rows.
--
-- Exists because hour-of-day utilisation is the most-asked question in
-- charging analytics, and a 24-row dimension carries day-part and peak-tariff
-- semantics that EXTRACT(hour FROM ...) does not.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_hour (
    hour_key             SMALLINT     NOT NULL,
    hour_label           VARCHAR(5)   NOT NULL,
    day_part             VARCHAR(16)  NOT NULL,
    is_peak_tariff_hour  BOOLEAN      NOT NULL,
    CONSTRAINT pk_dim_hour PRIMARY KEY (hour_key),
    CONSTRAINT ck_dim_hour_range CHECK (hour_key BETWEEN 0 AND 23)
);

COMMENT ON TABLE core.dim_hour IS
    'GRAIN: one row per hour of the IST day (0-23).';


-- ---------------------------------------------------------------------------
-- core.dim_customer - SCD Type 2.
--
-- Type 2: city, state, city_tier, customer_segment, subscription_plan,
--         kyc_status, is_active
-- Type 1: full_name_masked, email_domain, signup_date
--
-- Why the split: a customer relocating changes revenue-by-city attribution
-- from that date forward, and a plan upgrade must not retroactively reprice
-- last quarter. Correcting a misspelled name, by contrast, should fix every
-- historical version - it was always wrong, it was never different.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_customer (
    customer_sk            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    customer_id            VARCHAR(20)  NOT NULL,
    full_name_masked       VARCHAR(120) NULL,
    email_domain           VARCHAR(80)  NULL,
    city                   VARCHAR(60)  NULL,
    state                  VARCHAR(60)  NULL,
    city_tier              VARCHAR(8)   NULL,
    customer_segment       VARCHAR(20)  NOT NULL,
    subscription_plan      VARCHAR(20)  NOT NULL,
    kyc_status             VARCHAR(20)  NOT NULL,
    signup_date            DATE         NULL,
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    effective_from_utc     TIMESTAMPTZ  NOT NULL,
    effective_to_utc       TIMESTAMPTZ  NOT NULL DEFAULT '9999-12-31 00:00:00+00',
    is_current             BOOLEAN      NOT NULL DEFAULT TRUE,
    version_no             INT          NOT NULL DEFAULT 1,
    row_hash               CHAR(64)     NOT NULL,
    is_inferred            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    source_updated_at_utc  TIMESTAMPTZ  NULL,
    dw_run_id              UUID         NOT NULL,
    dw_inserted_at_utc     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    dw_updated_at_utc      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_dim_customer PRIMARY KEY (customer_sk),
    CONSTRAINT uq_dim_customer_version UNIQUE (customer_id, effective_from_utc),
    CONSTRAINT ck_dim_customer_validity CHECK (effective_to_utc > effective_from_utc),
    CONSTRAINT ck_dim_customer_current CHECK (
        is_current = (effective_to_utc = '9999-12-31 00:00:00+00')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uix_dim_customer_current
    ON core.dim_customer (customer_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS ix_dim_customer_pit
    ON core.dim_customer (customer_id, effective_from_utc, effective_to_utc);
CREATE INDEX IF NOT EXISTS ix_dim_customer_segment
    ON core.dim_customer (customer_segment) WHERE is_current;

COMMENT ON TABLE core.dim_customer IS
    'GRAIN: one row per customer_id per version-validity period. SCD Type 2 on segment/plan/kyc/location; Type 1 on name and email domain.';
COMMENT ON COLUMN core.dim_customer.row_hash IS
    'sha256 over the TYPE-2 TRACKED columns only, NULL-safe. A Type-1 column changing must not create a new version, so it must not be in the hash.';
COMMENT ON COLUMN core.dim_customer.effective_to_utc IS
    'EXCLUSIVE end of validity. The open version uses 9999-12-31 rather than NULL so range predicates need no COALESCE and the partial index stays simple.';


-- ---------------------------------------------------------------------------
-- core.dim_station - SCD Type 2.
--
-- Type 2: city, state, pincode, site_type, operator_name, num_bays, is_active
-- Type 1: station_name, address_line, latitude, longitude
--
-- num_bays is the load-bearing one: it is the denominator of every utilisation
-- figure. Comparing this month to last month using TODAY'S bay count silently
-- corrupts the trend for any site that was expanded.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_station (
    station_sk             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    station_id             VARCHAR(24)  NOT NULL,
    station_name           VARCHAR(120) NULL,
    address_line           VARCHAR(200) NULL,
    city                   VARCHAR(60)  NULL,
    state                  VARCHAR(60)  NULL,
    pincode                VARCHAR(10)  NULL,
    latitude               NUMERIC(9, 6) NULL,
    longitude              NUMERIC(9, 6) NULL,
    site_type              VARCHAR(20)  NULL,
    operator_name          VARCHAR(80)  NULL,
    num_bays               SMALLINT     NULL,
    commissioned_date      DATE         NULL,
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    effective_from_utc     TIMESTAMPTZ  NOT NULL,
    effective_to_utc       TIMESTAMPTZ  NOT NULL DEFAULT '9999-12-31 00:00:00+00',
    is_current             BOOLEAN      NOT NULL DEFAULT TRUE,
    version_no             INT          NOT NULL DEFAULT 1,
    row_hash               CHAR(64)     NOT NULL,
    is_inferred            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    source_updated_at_utc  TIMESTAMPTZ  NULL,
    dw_run_id              UUID         NOT NULL,
    dw_inserted_at_utc     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    dw_updated_at_utc      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_dim_station PRIMARY KEY (station_sk),
    CONSTRAINT uq_dim_station_version UNIQUE (station_id, effective_from_utc),
    CONSTRAINT ck_dim_station_validity CHECK (effective_to_utc > effective_from_utc),
    CONSTRAINT ck_dim_station_current CHECK (
        is_current = (effective_to_utc = '9999-12-31 00:00:00+00')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uix_dim_station_current
    ON core.dim_station (station_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS ix_dim_station_pit
    ON core.dim_station (station_id, effective_from_utc, effective_to_utc);

COMMENT ON TABLE core.dim_station IS
    'GRAIN: one row per station_id per version-validity period. num_bays is Type 2 because it is the utilisation denominator.';


-- ---------------------------------------------------------------------------
-- core.dim_tariff_plan - SCD Type 2. Price history IS the point.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_tariff_plan (
    tariff_plan_sk           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tariff_plan_id           VARCHAR(20)   NOT NULL,
    plan_name                VARCHAR(80)   NULL,
    price_per_kwh_inr        NUMERIC(8, 2)  NOT NULL DEFAULT 0,
    price_per_minute_inr     NUMERIC(8, 2)  NOT NULL DEFAULT 0,
    idle_fee_per_minute_inr  NUMERIC(8, 2)  NOT NULL DEFAULT 0,
    min_billable_kwh         NUMERIC(8, 3)  NOT NULL DEFAULT 0,
    gst_rate_pct             NUMERIC(5, 2)  NOT NULL DEFAULT 18,
    is_active                BOOLEAN       NOT NULL DEFAULT TRUE,
    effective_from_utc       TIMESTAMPTZ   NOT NULL,
    effective_to_utc         TIMESTAMPTZ   NOT NULL DEFAULT '9999-12-31 00:00:00+00',
    is_current               BOOLEAN       NOT NULL DEFAULT TRUE,
    version_no               INT           NOT NULL DEFAULT 1,
    row_hash                 CHAR(64)      NOT NULL,
    is_inferred              BOOLEAN       NOT NULL DEFAULT FALSE,
    is_deleted               BOOLEAN       NOT NULL DEFAULT FALSE,
    source_updated_at_utc    TIMESTAMPTZ   NULL,
    dw_run_id                UUID          NOT NULL,
    dw_inserted_at_utc       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    dw_updated_at_utc        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_dim_tariff_plan PRIMARY KEY (tariff_plan_sk),
    CONSTRAINT uq_dim_tariff_plan_version UNIQUE (tariff_plan_id, effective_from_utc),
    CONSTRAINT ck_dim_tariff_plan_validity CHECK (effective_to_utc > effective_from_utc),
    CONSTRAINT ck_dim_tariff_plan_current CHECK (
        is_current = (effective_to_utc = '9999-12-31 00:00:00+00')
    ),
    CONSTRAINT ck_dim_tariff_plan_prices CHECK (
        price_per_kwh_inr >= 0 AND price_per_minute_inr >= 0 AND idle_fee_per_minute_inr >= 0
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uix_dim_tariff_plan_current
    ON core.dim_tariff_plan (tariff_plan_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS ix_dim_tariff_plan_pit
    ON core.dim_tariff_plan (tariff_plan_id, effective_from_utc, effective_to_utc);

COMMENT ON TABLE core.dim_tariff_plan IS
    'GRAIN: one row per tariff_plan_id per version-validity period. The February session must resolve to February''s price, not today''s.';


-- ---------------------------------------------------------------------------
-- core.dim_charge_point - SCD Type 2. The flagship dimension.
--
-- Type 2: station_id, current_type, rated_power_kw, connector_type,
--         tariff_plan_id, firmware_version, status
-- Type 1: oem_vendor, model
--
-- rated_power_kw and tariff_plan_id are the two attributes with money and
-- analysis attached: a 30 -> 60 kW upgrade changes energy per session, and the
-- tariff plan the device points at decides what the customer was charged.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_charge_point (
    charge_point_sk        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    charge_point_id        VARCHAR(24)   NOT NULL,
    station_id             VARCHAR(24)   NULL,
    station_sk_current     BIGINT        NULL,
    oem_vendor             VARCHAR(40)   NULL,
    model                  VARCHAR(60)   NULL,
    current_type           VARCHAR(2)    NULL,
    rated_power_kw         NUMERIC(6, 2)  NULL,
    connector_type         VARCHAR(16)   NULL,
    tariff_plan_id         VARCHAR(20)   NULL,
    firmware_version       VARCHAR(16)   NULL,
    status                 VARCHAR(16)   NULL,
    commissioned_date      DATE          NULL,
    effective_from_utc     TIMESTAMPTZ   NOT NULL,
    effective_to_utc       TIMESTAMPTZ   NOT NULL DEFAULT '9999-12-31 00:00:00+00',
    is_current             BOOLEAN       NOT NULL DEFAULT TRUE,
    version_no             INT           NOT NULL DEFAULT 1,
    row_hash               CHAR(64)      NOT NULL,
    is_inferred            BOOLEAN       NOT NULL DEFAULT FALSE,
    is_deleted             BOOLEAN       NOT NULL DEFAULT FALSE,
    source_updated_at_utc  TIMESTAMPTZ   NULL,
    dw_run_id              UUID          NOT NULL,
    dw_inserted_at_utc     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    dw_updated_at_utc      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_dim_charge_point PRIMARY KEY (charge_point_sk),
    CONSTRAINT uq_dim_charge_point_version UNIQUE (charge_point_id, effective_from_utc),
    CONSTRAINT ck_dim_charge_point_validity CHECK (effective_to_utc > effective_from_utc),
    CONSTRAINT ck_dim_charge_point_current CHECK (
        is_current = (effective_to_utc = '9999-12-31 00:00:00+00')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uix_dim_charge_point_current
    ON core.dim_charge_point (charge_point_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS ix_dim_charge_point_pit
    ON core.dim_charge_point (charge_point_id, effective_from_utc, effective_to_utc);
CREATE INDEX IF NOT EXISTS ix_dim_charge_point_inferred
    ON core.dim_charge_point (charge_point_id) WHERE is_inferred;

COMMENT ON TABLE core.dim_charge_point IS
    'GRAIN: one row per charge_point_id per version-validity period. Type 2 on hardware, tariff assignment, firmware and status.';
COMMENT ON COLUMN core.dim_charge_point.station_sk_current IS
    'Denormalised convenience pointer to the station''s CURRENT version. Deliberate and documented: facts resolve the station point-in-time themselves and never use this column.';
COMMENT ON COLUMN core.dim_charge_point.is_inferred IS
    'TRUE when this row was created by a fact load for a device that had not yet appeared in the CMS extract. Promoted in place - same surrogate key - when the real record arrives, so existing facts become correct with no fact rewrite.';


-- ---------------------------------------------------------------------------
-- core.dim_vehicle - SCD Type 1, deliberately.
--
-- A vehicle's physical attributes do not change; only data corrections do, and
-- correcting a battery-capacity typo should fix all history rather than invent
-- a change event. Ownership can change on resale, but VoltHive attributes a
-- session to the customer ON the session, not to the vehicle's owner - so
-- ownership history has no analytical consumer.
--
-- Choosing Type 1 WITH A REASON is a stronger signal than making everything
-- Type 2.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_vehicle (
    vehicle_sk            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id            VARCHAR(20)   NOT NULL,
    customer_id_current   VARCHAR(20)   NULL,
    make                  VARCHAR(40)   NULL,
    model                 VARCHAR(60)   NULL,
    model_year            INT           NULL,
    battery_capacity_kwh  NUMERIC(6, 2)  NULL,
    connector_type        VARCHAR(16)   NULL,
    registration_state    VARCHAR(60)   NULL,
    vehicle_class         VARCHAR(16)   NULL,
    is_inferred           BOOLEAN       NOT NULL DEFAULT FALSE,
    dw_run_id             UUID          NOT NULL,
    dw_inserted_at_utc    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    dw_updated_at_utc     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_dim_vehicle PRIMARY KEY (vehicle_sk),
    CONSTRAINT uq_dim_vehicle_natural UNIQUE (vehicle_id)
);

COMMENT ON TABLE core.dim_vehicle IS
    'GRAIN: one row per vehicle_id, current state only. SCD Type 1 by deliberate decision - see docs/scd_policy.md.';


-- ---------------------------------------------------------------------------
-- core.dim_session_outcome - a small Type 1 "junk" dimension.
--
-- One row per distinct combination of session_status x stop_reason x
-- auth_method x is_roaming. It keeps four low-cardinality flags out of a
-- million-row fact and puts their grouped semantics (is_successful,
-- is_interrupted, outcome_group) in one place instead of in every query.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.dim_session_outcome (
    session_outcome_sk  INT          GENERATED BY DEFAULT AS IDENTITY,
    session_status      VARCHAR(16)  NOT NULL,
    stop_reason         VARCHAR(24)  NOT NULL,
    auth_method         VARCHAR(16)  NOT NULL,
    is_roaming          BOOLEAN      NOT NULL,
    is_successful       BOOLEAN      NOT NULL,
    is_interrupted      BOOLEAN      NOT NULL,
    outcome_group       VARCHAR(20)  NOT NULL,
    dw_run_id           UUID         NULL,
    dw_inserted_at_utc  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_dim_session_outcome PRIMARY KEY (session_outcome_sk),
    CONSTRAINT uq_dim_session_outcome_combo UNIQUE (
        session_status, stop_reason, auth_method, is_roaming
    )
);

COMMENT ON TABLE core.dim_session_outcome IS
    'GRAIN: one row per distinct (session_status, stop_reason, auth_method, is_roaming) combination. A junk dimension - roughly 60 rows.';


-- ---------------------------------------------------------------------------
-- Overlap-prevention exclusion constraints.
--
-- These make overlapping validity ranges STRUCTURALLY IMPOSSIBLE rather than
-- merely unlikely. They need the btree_gist extension (to mix an equality
-- operator on a scalar with an overlap operator on a range in one constraint),
-- which is not a trusted extension and so is created by the superuser during
-- database bootstrap - see docker/postgres/init/03_create_extensions.sh.
--
-- Guarded rather than assumed: if the extension is absent the schema still
-- applies, the DIM_NO_OVERLAPPING_VERSIONS quality rule still catches
-- violations after the fact, and a NOTICE says what was skipped. Failing the
-- whole DDL over an optional belt-and-braces constraint would be the wrong
-- trade.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    target RECORD;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'btree_gist') THEN
        RAISE NOTICE
            'btree_gist not installed - skipping SCD2 overlap exclusion constraints. '
            'The DIM_NO_OVERLAPPING_VERSIONS data-quality rule still detects violations.';
        RETURN;
    END IF;

    FOR target IN
        SELECT dim_name, key_col
        FROM (
            VALUES
            ('dim_customer', 'customer_id'),
            ('dim_station', 'station_id'),
            ('dim_tariff_plan', 'tariff_plan_id'),
            ('dim_charge_point', 'charge_point_id')
        ) AS t (dim_name, key_col)
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'ex_' || target.dim_name || '_no_overlap'
        ) THEN
            EXECUTE format(
                'ALTER TABLE core.%I ADD CONSTRAINT %I '
                'EXCLUDE USING gist (%I WITH =, '
                'tstzrange(effective_from_utc, effective_to_utc) WITH &&)',
                target.dim_name, 'ex_' || target.dim_name || '_no_overlap', target.key_col
            );
            RAISE NOTICE 'added overlap exclusion constraint on core.%', target.dim_name;
        END IF;
    END LOOP;
END
$$;
